### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by Wabo0** [pysel/dolev-strong#2]
Could you add some kind of open-source license, if you are open to that?
If so then, I'd like to use your code as part of a research project.

**Comment by pysel** [comment]
hello, absolutely, thank you for making an issue. 

however, I should point out that this is not the final version of the protocol, I know at least one major issue with the current implementation. if you are interested in this issue, you may contact me via any option listed in my profile, I will let you know about it

**Comment by pysel** [comment]
opened a PR that will add an MIT License to the codebase, please, approve a PR if that license works, thanks! https://github.com/pysel/dolev-strong/pull/3

cc: @Wabo0

**Comment by Wabo0** [comment]
Perfect - thank you!
